---

- hosts: all
  become: true
  tasks:

  - name: install updates
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: servers
  become: true
  tasks:

  - name: install apache2 & php support for apache packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
