- name: install apache and php packages
  tags: apache, php
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: copy html file for site
  tags: apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
